[package]
name = "Sunlight_Alarm"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = { git = "https://github.com/deviceplug/btleplug.git", branch = "master"}
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
